In [2]:
#Hard code
import numpy as np

def si_transition_matrix(beta):
    """
    Returns the 4x4 transition matrix for a 2-node SI model.
    
    State ordering:
    0 -> 00
    1 -> 01
    2 -> 10 
    3 -> 11
    """
    
    P = np.zeros((4,4))
    
    # 00 -> 00
    P[0,0] = 1.0
    
    # 01 -> 01 or 11
    P[1,1] = 1 - beta
    P[1,3] = beta
    
    # 10 -> 10 or 11
    P[2,2] = 1 - beta
    P[2,3] = beta
    
    # 11 -> 11 (absorbing)
    P[3,3] = 1.0
    
    return P


# Example usage
beta = 0.3
P = si_transition_matrix(beta)
print(P)


[[1.  0.  0.  0. ]
 [0.  0.7 0.  0.3]
 [0.  0.  0.7 0.3]
 [0.  0.  0.  1. ]]


In [ ]:
#Constructing algorithmically
import numpy as np
import matplotlib.pyplot as plt
import random

init = [0,1,1,0,0]

#Customize the initial condition - adjaceny matrix is fixed
def SIModel_viaDTMC(beta,gamma,x0,N):
    
    x_0=[3]
    x_1=[2]
    x_2=[0]
    y=[0]
    num_susceptible, num_infected, num_removed = 3, 2, 0
    average_susceptible = average_infected = average_removed = 0
    
    
    #Define the adjacency matrix 
    adj = np.zeros((5,5))
    adj[0,1:5]=adj[1:5,0]=1
    k= len(adj)
    print(adj)
    
    
    #Define the matrix containing all states/time steps
    X = np.zeros((len(x0),N+1))
    i=0
    
    
    #Loop
    while i< len(x0):
        X[i,0]=x0[i]
        i+=1
    
    matrix = np.zeros((2,3))
    f=0
    for t in range(1,N+1): #each time step:
        while f <= 2:
            for j in range(k): #go through each element of the *newest* state
                if X[j, t-1] == -1:
                    X[j, t]=-1
                elif X[j, t-1] == 1:
                    f = random.random()
                    if f<gamma:
                        X[j, t]=-1
                        num_infected-=1
                        num_removed+=1
                    else:
                        X[j, t]=1

                elif X[j, t-1]==0:
                    n = adj@ X[:, t-1]
                    p = 1-((1-beta)**n[j])
                    r = random.random()
                    if r<p:
                        X[j, t]=1
                        num_infected+=1
                        num_susceptible-=1
                    else:
                        X[j, t]=0

            matrix[int(f):0]= num_susceptible
            matrix[int(f):1]= num_infected
            matrix[int(f):2]=num_removed
            f+=1
        
        average_susceptible = (sum(matrix[:,0]))/2
        average_infected = (sum(matrix[:,1]))/2
        average_removed = (sum(matrix[:,2]))/2
            
        x_0.append(average_susceptible)
        x_1.append(average_infected)
        x_2.append(average_removed)
        y.append(t)
        
        
    
    
    #Graph
    plt.plot(y, x_0, label = "susceptible")
    plt.plot(y, x_1, '-.', label = "infected")
    plt.plot(y, x_2, '-*', label = "removed")
    plt.title(f"Beta = {beta} Gamma = {gamma}")
    plt.legend()
    plt.ylim([0,N])
    return X


SIModel_viaDTMC(0.5, 0.5,init, 5)

[[0. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]]


In [ ]:
#reminding myself how random works
import random
print(random.random())

In [ ]:
#Constructing algorithmically
import numpy as np
import matplotlib.pyplot as plt
import random

init = [0,1,1,0,0]

#Customize the initial condition - adjaceny matrix is fixed
def SIModel_viaDTMC(beta,gamma,N,nodes):
    x_1=[1]
    x_2=[0]
    y=[0]
    num_susceptible = 499    
    x_0=[num_susceptible,]
    num_infected = x_1[0]
    num_removed = x_2[0]
    #Define the adjacency matrix - complete graph
    adj = np.zeros((nodes,nodes))
    adj[0:nodes,0:nodes]=1

    for s in range(nodes):
        adj[s,s] = 0 
    print(adj)
    k= len(adj)
    
    #Define inish condish
    init = []
    num=0
    while num < nodes-1:
        init.append(0)
        num+=1
    init.append(1)

    #Define the matrix containing all states/time steps
    X = np.zeros((len(init),N+1))
    i=0
    while i< len(init):
        X[i,0]=init[i]
        i+=1
    
    for t in range(1,N+1): #each time step:
        for j in range(k): #go through each element of the *newest* state, if infected => stays infected
            if X[j, t-1] == -1:
                X[j, t]=-1
            elif X[j, t-1] == 1:
                f = random.random()
                if f<gamma:
                    X[j, t]=-1
                    num_infected-=1
                    num_removed+=1
                else:
                    X[j, t]=1
            elif X[j, t-1]==0:
                n = adj@ X[:, t-1]
                p = 1-((1-beta)**n[j])
                r = random.random()
                if r<p:
                    X[j, t]=1
                    num_infected+=1
                    num_susceptible-=1
                else:
                    X[j, t]=0
            
            
        x_0.append(num_susceptible)
        x_1.append(num_infected)
        x_2.append(num_removed)
        y.append(t)

    plt.plot(y, x_0, label = "susceptible")
    plt.plot(y, x_1, '-.', label = "infected")
    plt.plot(y, x_2, '-*', label = "removed")
    plt.title(f"Beta = {beta} Gamma = {gamma}")
    plt.legend()
    plt.ylim([0,500])
    
    return X


SIModel_viaDTMC(0.5, 0.03, 100, 500)

#Customize the adjacency matrix/connectivity of the graph

In [ ]:
import numpy as np
nodes = 3
adj = np.zeros((nodes,nodes))
adj[0:nodes,0:nodes]=1

for s in range(nodes):
    adj[s,s] = 0 

print(adj)

In [ ]:
init = []
nodes=10
num=0
while num <= nodes:
    init.append(random.randint(0,1))
    num+=1
print(init)

In [ ]:
#Constructing algorithmically
import numpy as np
import matplotlib.pyplot as plt
import random


#Customize the initial condition - adjaceny matrix is fixed
def SIModel_viaDTMC(beta, N,nodes):
    x_0=[3]
    x_1=[2]
    y=[0]
    num_susceptible = 3
    num_infected = 2
    #Define the adjacency matrix - dumbell graph
    adj = [[0,1,1,1,0,0,0,0],
           [1,0,1,1,0,0,0,0],
           [1,1,0,1,0.2,0,0,0],
           [1,1,1,0,0,0,0,0],
           [0,0,0.2,0,0,1,1,1],
           [0,0,0,0,1,0,1,1],
           [0,0,0,0,1,1,0,1],
           [0,0,0,0,1,1,1,0]
          ]

    k= len(adj)
    
    #Define inish condish
    init = [0,0,0,0,0,0,1,0]
    

    #Define the matrix containing all states/time steps
    X = np.zeros((len(init),N+1))
    i=0
    while i< len(init):
        X[i,0]=init[i]
        i+=1
    
    for t in range(1,N+1): #each time step:
        for j in range(k): #go through each element of the *newest* state, if infected => stays infected
            if X[j, t-1] == 1:
                X[j, t]=1
            elif X[j, t-1]==0:
                n = adj@ X[:, t-1]
                p = 1-((1-beta)**n[j])
                r = random.random()
                if r<p:
                    X[j, t]=1
                    num_infected+=1
                    num_susceptible-=1
                else:
                    X[j, t]=0
            
            
        x_0.append(num_susceptible)
        x_1.append(num_infected)
        y.append(t)

    plt.plot(y, x_0, label = "susceptible")
    plt.plot(y, x_1, '-.', label = "infected")
    plt.title(f"Beta = {beta}")
    plt.legend()
    plt.ylim([0,5])
    print(x_0)  
    return X


SIModel_viaDTMC(0.7, 10, 10)

#Customize the adjacency matrix/connectivity of the graph

In [ ]:
#Add removed parameter
#Constructing algorithmically
import numpy as np
import matplotlib.pyplot as plt
import random


#Customize the initial condition - adjaceny matrix is fixed
def SIModel_viaDTMC(beta, N,nodes):
    x_0=[3]
    x_1=[2]
    y=[0]
    num_susceptible = 3
    num_infected = 2
    #Define the adjacency matrix - dumbell graph
    adj = [[0,1,1,1,0,0,0,0],
           [1,0,1,1,0,0,0,0],
           [1,1,0,1,0.2,0,0,0],
           [1,1,1,0,0,0,0,0],
           [0,0,0.2,0,0,1,1,1],
           [0,0,0,0,1,0,1,1],
           [0,0,0,0,1,1,0,1],
           [0,0,0,0,1,1,1,0]
          ]

    k= len(adj)
    
    #Define inish condish
    init = [0,0,0,0,0,0,1,0]
    

    #Define the matrix containing all states/time steps
    X = np.zeros((len(init),N+1))
    i=0
    while i< len(init):
        X[i,0]=init[i]
        i+=1
    
    for t in range(1,N+1): #each time step:
        for j in range(k): #go through each element of the *newest* state, if infected => stays infected
            if X[j, t-1] == 1:
                X[j, t]=1
            elif X[j, t-1]==0:
                n = adj@ X[:, t-1]
                p = 1-((1-beta)**n[j])
                r = random.random()
                if r<p:
                    X[j, t]=1
                    num_infected+=1
                    num_susceptible-=1
                else:
                    X[j, t]=0
            
            
        x_0.append(num_susceptible)
        x_1.append(num_infected)
        y.append(t)

    plt.plot(y, x_0, label = "susceptible")
    plt.plot(y, x_1, '-.', label = "infected")
    plt.title(f"Beta = {beta}")
    plt.legend()
    plt.ylim([0,5])
    print(x_0)  
    return X


SIModel_viaDTMC(0.7, 10, 10)

#Customize the adjacency matrix/connectivity of the graph